steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/speech-to-text:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/speech-to-text:latest'
      - '.'
    timeout: 1200s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/speech-to-text:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/speech-to-text:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'speech-to-text'
      - '--image'
      - 'gcr.io/$PROJECT_ID/speech-to-text:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/speech-to-text:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/speech-to-text:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  timeout: 1800s
